import { PlatformShell } from "@/components/PlatformShell";
import { useLanguage } from "@/lib/i18n";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, ClipboardCheck, Leaf, Loader2, ShieldCheck } from "lucide-react";
import { useRoute } from "wouter";

type Draft = { summary?: string; assumptions?: string[]; missingCriticalData?: string[]; preliminaryApproach?: string[]; expertReviewFocus?: string[]; safetyNote?: string };

export default function SharedReport() {
  const [, params] = useRoute("/reports/:shareToken"); const { language } = useLanguage(); const isArabic = language === "ar";
  const query = trpc.workspace.design.byShareToken.useQuery({ shareToken: params?.shareToken || "missing" }, { enabled: Boolean(params?.shareToken) });
  if (query.isLoading) return <PlatformShell compact><main className="container grid min-h-[60vh] place-items-center"><Loader2 className="size-7 animate-spin text-[#648534]" /></main></PlatformShell>;
  if (!query.data) return <PlatformShell compact title={isArabic ? "التقرير غير متاح" : "Report unavailable"} eyebrow={isArabic ? "قد يكون الرابط غير صحيح أو لم يتم اعتماد التقرير بعد" : "The link may be invalid or the report has not been finalized"}><main className="container py-12"><div className="mx-auto max-w-xl rounded-[1.6rem] border border-[#e9c5bd] bg-[#fff8f6] p-8 text-center"><AlertTriangle className="mx-auto size-8 text-[#a56a3d]" /><h2 className="mt-4 text-xl font-bold text-[#704821]">{isArabic ? "لا يمكن عرض التقرير الآن" : "This report cannot be displayed now"}</h2><p className="mt-2 text-sm leading-6 text-[#876a41]">{isArabic ? "يتاح التقرير المشترك بعد اعتماد الخبير للمسودة النهائية." : "A shared report becomes available after an expert approves the final draft."}</p></div></main></PlatformShell>;
  const draft = query.data.design.draftData as Draft | null;
  return <PlatformShell compact title={isArabic ? "تقرير تصميم زراعي" : "Agricultural design report"} eyebrow={isArabic ? "نسخة مشتركة ومعتمدة للمراجعة" : "A shared version approved for review"}><main className="container py-8"><section className="mx-auto max-w-4xl overflow-hidden rounded-[1.8rem] border border-[#35530e]/10 bg-white shadow-[0_18px_50px_rgba(48,67,22,.08)]"><div className="bg-[#35530e] p-7 text-white sm:p-9"><div className="flex items-start justify-between gap-5"><div><p className="text-xs font-bold tracking-[.14em] text-[#d8e9b7]">{query.data.design.designType.toUpperCase()}</p><h2 className="mt-3 text-2xl font-bold">{query.data.design.title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#dce9ca]">{isArabic ? "تقرير مشترك يوضح المسودة والافتراضات وحدود الاستخدام؛ لا يحل محل الزيارة أو القياسات المطلوبة للموقع." : "A shared report presenting the draft, assumptions, and use limits; it does not replace required site measurements or a field visit."}</p></div><ShieldCheck className="size-8 text-[#dceebf]" /></div></div><div className="p-6 sm:p-9"><ReportSection icon={ClipboardCheck} title={isArabic ? "الملخص" : "Summary"}><p>{draft?.summary || (isArabic ? "المسودة المعتمدة متاحة للمراجعة." : "The approved draft is available for review.")}</p></ReportSection><div className="mt-7 grid gap-5 md:grid-cols-2"><ReportList icon={Leaf} title={isArabic ? "الافتراضات" : "Assumptions"} items={draft?.assumptions} fallback={isArabic ? "تُراجع الافتراضات مع بيانات الموقع." : "Assumptions are reviewed against site data."} /><ReportList icon={AlertTriangle} title={isArabic ? "بيانات ما زالت مطلوبة" : "Information still needed"} items={draft?.missingCriticalData} fallback={isArabic ? "يستمر التحقق قبل أي تنفيذ." : "Verification continues before implementation."} /></div><ReportList icon={CheckCircle2} title={isArabic ? "المسار المبدئي" : "Preliminary approach"} items={draft?.preliminaryApproach} fallback={isArabic ? "تُستكمل خطوات التنفيذ وفق قياسات الموقع ومراجعة الخبير." : "Implementation steps are completed with site measurement and expert review."} /><div className="mt-7 rounded-2xl border border-[#e9d4a8] bg-[#fffaf0] p-4 text-sm leading-6 text-[#81652f]"><strong>{isArabic ? "ملاحظة السلامة: " : "Safety note: "}</strong>{draft?.safetyNote || (isArabic ? "هذا التقرير إرشادي ويحتاج تحققًا ميدانيًا قبل التنفيذ." : "This report is advisory and requires field verification before implementation.")}</div></div></section></main></PlatformShell>;
}
function ReportSection({ icon: Icon, title, children }: { icon: typeof ClipboardCheck; title: string; children: React.ReactNode }) { return <section><h3 className="flex items-center gap-2 font-bold text-[#334b17]"><Icon className="size-5 text-[#668833]" />{title}</h3><div className="mt-3 text-sm leading-7 text-[#68775a]">{children}</div></section>; }
function ReportList({ icon: Icon, title, items, fallback }: { icon: typeof Leaf; title: string; items?: string[]; fallback: string }) { return <section className="mt-7 rounded-2xl bg-[#f7f9f4] p-4"><h3 className="flex items-center gap-2 font-bold text-[#334b17]"><Icon className="size-5 text-[#668833]" />{title}</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-[#68775a]">{items?.length ? items.map(item => <li key={item} className="flex gap-2"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-[#85a855]" />{item}</li>) : <li>{fallback}</li>}</ul></section>; }
