import { AccessGate, PlatformShell } from "@/components/PlatformShell";
import PlantCatalogManager from "@/components/PlantCatalogManager";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/_core/hooks/useAuth";
import { useLanguage } from "@/lib/i18n";
import { trpc } from "@/lib/trpc";
import { addCatalogPlant, getCatalog, removeCatalogPlant, updateCatalogPlant, type EditablePlant } from "@/data/plantCatalog";
import { BarChart3, BookOpen, ClipboardCheck, Leaf, Loader2, LockKeyhole, Plus, ShieldCheck, UsersRound } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const categories = ["plant", "crop", "tree", "disease", "pest", "irrigation", "region"] as const;

export default function Control() {
  const { user } = useAuth(); const { language } = useLanguage();
  return <PlatformShell title={language === "ar" ? "مركز التحكم" : "Control center"} eyebrow={language === "ar" ? "الإشراف على جودة المحتوى والمراجعات والتشغيل" : "Oversight for content quality, reviews, and operations"}><AccessGate>{user?.role === "user" ? <main className="container py-12"><div className="mx-auto max-w-lg rounded-[1.6rem] border border-[#ead1a6] bg-[#fffaf0] p-8 text-center"><LockKeyhole className="mx-auto size-9 text-[#9b7430]" /><h2 className="mt-4 text-xl font-bold text-[#6f5223]">{language === "ar" ? "هذه المساحة للمختصين والإدارة" : "This space is for experts and administrators"}</h2><p className="mt-3 text-sm leading-6 text-[#886e42]">{language === "ar" ? "يتم منح صلاحيات المراجعة وإدارة المحتوى من خلال الإدارة." : "Review and content-management access is granted by administration."}</p></div></main> : <ControlContent />}</AccessGate></PlatformShell>;
}

function ControlContent() {
  const { user } = useAuth(); const { language } = useLanguage(); const isAdmin = user?.role === "admin";
  const summary = trpc.control.summary.useQuery(undefined, { enabled: isAdmin, staleTime: 30_000, refetchOnWindowFocus: false, placeholderData: { users: 0, projects: 0, analyses: 0, pendingReviews: 0 } });
  const metrics = [{ icon: UsersRound, label: language === "ar" ? "المستخدمون" : "Users", value: summary.data?.users ?? "—" }, { icon: ClipboardCheck, label: language === "ar" ? "المشاريع" : "Projects", value: summary.data?.projects ?? "—" }, { icon: Leaf, label: language === "ar" ? "التحليلات" : "Analyses", value: summary.data?.analyses ?? "—" }, { icon: BarChart3, label: language === "ar" ? "بانتظار المراجعة" : "Pending reviews", value: summary.data?.pendingReviews ?? "—" }];
  return <main className="container py-8"><section className="rounded-[1.6rem] bg-[#35530e] p-6 text-white sm:flex sm:items-center sm:justify-between"><div><p className="text-xs font-bold tracking-[.14em] text-[#d6e8b5]">{isAdmin ? (language === "ar" ? "إدارة المنصة" : "PLATFORM ADMINISTRATION") : (language === "ar" ? "مراجعة خبيرة" : "EXPERT REVIEW")}</p><h2 className="mt-2 text-2xl font-bold">{language === "ar" ? "ضبط الجودة الزراعية والتشغيل" : "Agricultural quality & operations"}</h2></div><ShieldCheck className="mt-4 size-9 text-[#d9ebba] sm:mt-0" /></section>{isAdmin && <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(metric => <article key={metric.label} className="rounded-2xl border border-[#35530e]/10 bg-white p-5"><metric.icon className="size-5 text-[#668833]" /><p className="mt-4 text-2xl font-bold text-[#304515]">{summary.isLoading ? <Loader2 className="size-5 animate-spin" /> : metric.value}</p><p className="mt-1 text-xs font-bold text-[#718062]">{metric.label}</p></article>)}</section>}
  {isAdmin && <><PlantCatalogManager /><KnowledgeManager /></>}</main>;
}

function KnowledgeManager() {
  const { language } = useLanguage(); const utils = trpc.useUtils(); const list = trpc.control.knowledge.list.useQuery();
  const [category, setCategory] = useState<(typeof categories)[number]>("plant"); const [nameAr, setNameAr] = useState(""); const [nameEn, setNameEn] = useState(""); const [summaryAr, setSummaryAr] = useState(""); const [summaryEn, setSummaryEn] = useState("");
  const create = trpc.control.knowledge.create.useMutation({ onSuccess: () => { toast.success(language === "ar" ? "تم حفظ عنصر المعرفة" : "Knowledge item saved"); setNameAr(""); setNameEn(""); setSummaryAr(""); setSummaryEn(""); utils.control.knowledge.list.invalidate(); utils.knowledge.list.invalidate(); }, onError: error => toast.error(error.message) });
  const save = (event: FormEvent) => { event.preventDefault(); create.mutate({ category, nameAr, nameEn, summaryAr, summaryEn, status: "review" }); };
  return <section className="mt-6 grid gap-5 xl:grid-cols-[1fr_.9fr]"><div className="rounded-[1.6rem] border border-[#35530e]/10 bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#eff4e9] text-[#35530e]"><BookOpen className="size-5" /></span><div><p className="text-xs font-bold tracking-[.14em] text-[#78924a]">{language === "ar" ? "محتوى المعرفة" : "KNOWLEDGE CONTENT"}</p><h2 className="mt-1 text-xl font-bold text-[#314617]">{language === "ar" ? "إضافة مرجع للمراجعة" : "Add a reference for review"}</h2></div></div><form onSubmit={save} className="mt-5 grid gap-3 sm:grid-cols-2"><Select value={category} onValueChange={value => setCategory(value as typeof category)}><SelectTrigger className="h-10 rounded-xl"><SelectValue /></SelectTrigger><SelectContent>{categories.map(item => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><div className="rounded-xl bg-[#fff8ec] px-3 py-2 text-xs leading-5 text-[#876b34]">{language === "ar" ? "تُحفظ المراجع الجديدة للمراجعة قبل النشر." : "New references are saved for review before publication."}</div><Input value={nameAr} onChange={event => setNameAr(event.target.value)} required placeholder="الاسم بالعربية" className="h-10 rounded-xl" /><Input value={nameEn} onChange={event => setNameEn(event.target.value)} required placeholder="Name in English" className="h-10 rounded-xl" /><Textarea value={summaryAr} onChange={event => setSummaryAr(event.target.value)} required placeholder="ملخص عربي مراجع" className="min-h-28 rounded-xl" /><Textarea value={summaryEn} onChange={event => setSummaryEn(event.target.value)} required placeholder="Reviewed English summary" className="min-h-28 rounded-xl" /><Button type="submit" disabled={create.isPending} className="h-10 rounded-xl bg-[#35530e] text-white hover:bg-[#294108] sm:col-span-2">{create.isPending ? <Loader2 className="size-4 animate-spin" /> : <Plus className="size-4" />}{language === "ar" ? "إضافة للمراجعة" : "Add for review"}</Button></form></div><div className="rounded-[1.6rem] border border-[#35530e]/10 bg-white p-5 sm:p-6"><h2 className="text-xl font-bold text-[#314617]">{language === "ar" ? "حالة المحتوى" : "Content status"}</h2><div className="mt-4 space-y-2">{list.data?.slice(0, 6).map(item => <div key={item.id} className="rounded-xl bg-[#f7f9f4] px-3 py-3"><div className="flex items-center justify-between gap-3"><strong className="text-sm text-[#405525]">{language === "ar" ? item.nameAr : item.nameEn}</strong><span className="rounded-full bg-white px-2 py-1 text-[10px] font-bold text-[#6d843f]">{item.status}</span></div><p className="mt-1 text-xs text-[#728062]">{item.category}</p></div>)}{!list.isLoading && !list.data?.length && <p className="rounded-xl border border-dashed border-[#c3d4ae] p-4 text-center text-sm text-[#718062]">{language === "ar" ? "لا توجد عناصر معرفة بعد." : "No knowledge items yet."}</p>}</div></div></section>;
}
