import { AccessGate, AdminGate, PlatformShell } from "@/components/PlatformShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { documentTypeLabel, emptyDocument, getDocuments, removeDocument, saveDocument, subscribeToDocuments, type DocumentType, type FinancialDocument, type InvoiceRow, type PaymentMethod } from "@/data/financialDocuments";
import { FileDown, Plus, Printer, Save, ShoppingCart, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

const tabs: DocumentType[] = ["exportInvoice", "purchaseOrder", "receipt", "disbursement"];
const paymentLabels: Record<PaymentMethod, string> = { cash: "نقداً", check: "شيك", transfer: "تحويل", online: "أونلاين" };
const updateRow = (rows: InvoiceRow[], index: number, key: keyof InvoiceRow, value: string) => rows.map((row, i) => i === index ? { ...row, [key]: value } : row);

export default function FinancialDocuments() {
  const [type, setType] = useState<DocumentType>("exportInvoice");
  const [documents, setDocuments] = useState<FinancialDocument[]>(() => getDocuments());
  const [doc, setDoc] = useState<FinancialDocument>(() => emptyDocument("exportInvoice"));
  const [query, setQuery] = useState("");
  useEffect(() => subscribeToDocuments(() => setDocuments(getDocuments())), []);
  useEffect(() => {
    const handleCommand = (event: Event) => {
      const content = (event as CustomEvent<{ content?: string }>).detail?.content?.trim() || "";
      if (!content) return;
      const lower = content.toLocaleLowerCase();
      const nextType: DocumentType = /طلب\s*شراء|شراء/.test(lower) ? "purchaseOrder" : /سند\s*قبض|وصل\s*قبض/.test(lower) ? "receipt" : /سند\s*صرف|وصل\s*صرف/.test(lower) ? "disbursement" : /فاتورة|تصدير/.test(lower) ? "exportInvoice" : type;
      setType(nextType);
      setDoc(current => ({ ...current, type: nextType }));
    };
    window.addEventListener("financial-ai-command", handleCommand);
    return () => window.removeEventListener("financial-ai-command", handleCommand);
  }, [type]);
  const filtered = useMemo(() => documents.filter(item => item.type === type && `${item.number} ${item.personName} ${item.destination} ${item.sourceName} ${item.supplier}`.includes(query)), [documents, type, query]);
  const changeType = (next: DocumentType) => { setType(next); setDoc(emptyDocument(next)); };
  const patch = (changes: Partial<FinancialDocument>) => setDoc(current => ({ ...current, ...changes }));
  const addRow = () => patch({ rows: [...doc.rows, { item: "", weight: "", quantity: "", origin: "", notes: "", dinar: "0", fils: "000" }] });
  const save = () => { saveDocument(doc); setDocuments(getDocuments()); };
  return <AccessGate><AdminGate><PlatformShell title="الفواتير والسندات" eyebrow="إدارة المستندات المالية"><main className="container py-8" dir="rtl">
    <style>{`@media print { body * { visibility: hidden !important; } #financial-document, #financial-document * { visibility: visible !important; } #financial-document { position: absolute; inset: 0; width: 100%; } .no-print { display: none !important; } }`}</style>
    <section className="no-print relative overflow-hidden rounded-[1.6rem] bg-[#064b3a] p-6 text-white shadow-[0_18px_45px_rgba(6,75,58,.18)]"><div className="absolute -left-10 -top-16 size-48 rounded-full bg-[#c8a75a]/20 blur-2xl" /><p className="relative text-xs font-bold tracking-[.16em] text-[#bde1c9]">QADRI AGRICULTURE · ADMIN</p><h1 className="relative mt-2 text-3xl font-black">الفواتير والسندات</h1><p className="relative mt-2 text-sm text-[#d5eee3]">أنشئ واحفظ واطبع مستندات المؤسسة بتنسيق رسمي موحّد.</p></section>
    <div className="no-print mt-6 flex flex-wrap gap-2">{tabs.map(item => <button key={item} type="button" onClick={() => changeType(item)} className={`rounded-xl px-4 py-3 text-sm font-bold transition ${type === item ? "bg-[#0a4b39] text-white shadow-md" : "border border-[#cfe0d6] bg-white text-[#49665b] hover:border-[#8ab8a3]"}`}>{item === "purchaseOrder" && <ShoppingCart className="me-2 inline size-4" />}{documentTypeLabel(item)}</button>)}</div>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_1.35fr]">
      <section className="no-print rounded-2xl border border-[#d8e7dd] bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold text-[#7a9a8a]">ARCHIVE</p><h2 className="text-lg font-black text-[#17342d]">المحفوظات</h2></div><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="بحث..." className="h-9 w-36 rounded-lg" /></div><div className="mt-4 space-y-2">{filtered.map(item => <div key={item.id} className="flex items-center justify-between gap-2 rounded-xl bg-[#f4f8f4] p-3"><button type="button" className="min-w-0 flex-1 text-start" onClick={() => setDoc(item)}><b className="block truncate text-sm">{item.number}</b><span className="text-xs text-[#6c8177]">{item.date} · {item.personName || item.destination || item.supplier || item.sourceName || "بدون اسم"}</span></button><button type="button" onClick={() => { removeDocument(item.id); setDocuments(getDocuments()); }} className="rounded-lg p-2 text-red-700" aria-label="حذف"><Trash2 className="size-4" /></button></div>)}{!filtered.length && <p className="rounded-xl border border-dashed p-4 text-center text-sm text-[#71877c]">لا توجد مستندات محفوظة.</p>}</div></section>
      <section id="financial-document" className={`rounded-2xl border-2 bg-white p-5 shadow-[0_18px_50px_rgba(20,69,48,.10)] sm:p-8 ${type === "purchaseOrder" ? "border-[#c8a75a]" : "border-[#174d3b]"}`}>
        <DocumentHeader doc={doc} type={type} />
        {type === "exportInvoice" ? <ExportForm doc={doc} patch={patch} addRow={addRow} /> : type === "purchaseOrder" ? <PurchaseOrderForm doc={doc} patch={patch} addRow={addRow} /> : <VoucherForm type={type} doc={doc} patch={patch} />}
        <div className="no-print mt-6 flex flex-wrap gap-2 border-t pt-5"><Button onClick={save} className="bg-[#0a4b39] text-white"><Save className="me-2 size-4" />حفظ المستند</Button><Button onClick={() => setDoc(emptyDocument(type))} variant="outline"><Plus className="me-2 size-4" />مستند جديد</Button><Button onClick={() => window.print()} variant="outline"><Printer className="me-2 size-4" />طباعة / PDF</Button><Button onClick={() => window.print()} variant="outline"><FileDown className="me-2 size-4" />PDF صفحة واحدة</Button></div>
      </section>
    </div>
  </main></PlatformShell></AdminGate></AccessGate>;
}
function DocumentHeader({ doc, type }: { doc: FinancialDocument; type: DocumentType }) { return <div className={`flex items-start justify-between gap-4 border-b-2 pb-5 ${type === "purchaseOrder" ? "border-[#c8a75a]" : "border-[#c8a75a]"}`}><div className="flex items-center gap-3"><img src="/assets/qadri-logo.png" alt="شعار مؤسسة القادري الزراعية" className="size-16 object-contain" /><div><h2 className="text-2xl font-black text-[#174d3b]">مؤسسة القادري الزراعية</h2><p className="mt-1 text-sm font-semibold text-[#60766b]">{doc.address || "جرش - طريق عمان"}</p><p className="mt-1 text-[10px] font-bold tracking-[.14em] text-[#c19b42]">QADRI AGRICULTURE EST.</p></div></div><div className="text-end"><p className="mb-2 inline-block rounded-full bg-[#f6edcf] px-3 py-1 text-[10px] font-black tracking-[.12em] text-[#7d6125]">OFFICIAL DOCUMENT</p><h1 className="text-2xl font-black text-[#174d3b]">{documentTypeLabel(type)}</h1><p className="mt-2 text-sm">رقم: <b>{doc.number}</b> · التاريخ: <b>{doc.date}</b></p></div></div>; }
function Field({ label, value, onChange, multiline = false, placeholder }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean; placeholder?: string }) { return <label className="block"><span className="mb-1 block text-xs font-bold text-[#48635a]">{label}</span>{multiline ? <Textarea value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} className="min-h-20 rounded-lg" /> : <Input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} className="h-10 rounded-lg" />}</label>; }
function ItemTable({ doc, patch, addRow, purchase = false }: { doc: FinancialDocument; patch: (changes: Partial<FinancialDocument>) => void; addRow: () => void; purchase?: boolean }) { const headers = purchase ? ["الصنف / الوصف", "الوحدة", "الكمية", "السعر بالدينار", "الإجمالي", "ملاحظات"] : ["الصنف", "الوزن", "الكمية", "المنشأ", "ملاحظات", "دينار", "فلس"]; const keys = purchase ? (["item", "origin", "quantity", "dinar", "fils", "notes"] as (keyof InvoiceRow)[]) : (["item", "weight", "quantity", "origin", "notes", "dinar", "fils"] as (keyof InvoiceRow)[]); return <><div className="overflow-x-auto"><table className="w-full min-w-[720px] border-collapse text-sm"><thead><tr className="bg-[#edf5ee]">{headers.map(h => <th key={h} className="border border-[#cfe0d6] p-2 text-[#224b3d]">{h}</th>)}</tr></thead><tbody>{doc.rows.map((row, i) => <tr key={i}>{keys.map(key => <td key={key} className="border border-[#d8e7dd] p-1"><Input value={row[key]} onChange={e => patch({ rows: updateRow(doc.rows, i, key, e.target.value) })} className="h-9 min-w-20 rounded-md border-0 bg-transparent" /></td>)}</tr>)}</tbody></table></div><Button type="button" onClick={addRow} variant="outline" className="no-print mt-3"><Plus className="me-2 size-4" />إضافة بند</Button></>; }
function ExportForm({ doc, patch, addRow }: { doc: FinancialDocument; patch: (changes: Partial<FinancialDocument>) => void; addRow: () => void }) { return <div className="mt-6 space-y-5"><div className="grid gap-3 sm:grid-cols-2"><Field label="اسم المصدر / المنشأة" value={doc.sourceName} onChange={sourceName => patch({ sourceName })} /><Field label="رقم المنشأة" value={doc.facilityNumber} onChange={facilityNumber => patch({ facilityNumber })} /><Field label="الجهة المصدر إليها" value={doc.destination} onChange={destination => patch({ destination })} /><Field label="العنوان" value={doc.address} onChange={address => patch({ address })} /></div><ItemTable doc={doc} patch={patch} addRow={addRow} /><div className="grid gap-3 sm:grid-cols-2"><Field label="المجموع بالدينار" value={doc.totalDinar} onChange={totalDinar => patch({ totalDinar })} /><Field label="المجموع بالفلس" value={doc.totalFils} onChange={totalFils => patch({ totalFils })} /><Field label="المجموع كتابةً" value={doc.totalInWords} onChange={totalInWords => patch({ totalInWords })} placeholder="اكتب المجموع بالحروف" /><Field label="نص الشهادة" value={doc.certificateText} onChange={certificateText => patch({ certificateText })} multiline /><Field label="عبارة السماح بالتصدير" value={doc.exportPermissionText} onChange={exportPermissionText => patch({ exportPermissionText })} multiline /></div></div>; }
function PurchaseOrderForm({ doc, patch, addRow }: { doc: FinancialDocument; patch: (changes: Partial<FinancialDocument>) => void; addRow: () => void }) { return <div className="mt-6 space-y-5"><div className="rounded-xl bg-[#fbf6e5] p-4 text-sm text-[#6f5624]"><b>طلب شراء داخلي</b><p className="mt-1">يرجى اعتماد وتوفير الأصناف الموضحة أدناه حسب الحاجة التشغيلية للمؤسسة.</p></div><div className="grid gap-3 sm:grid-cols-2"><Field label="الجهة / المورد المقترح" value={doc.supplier} onChange={supplier => patch({ supplier })} placeholder="اكتب الجهة أو المورد" /><Field label="طالب الشراء" value={doc.requester} onChange={requester => patch({ requester })} /><Field label="القسم" value={doc.department} onChange={department => patch({ department })} /><Field label="التاريخ المتوقع للتوريد" value={doc.expectedDate} onChange={expectedDate => patch({ expectedDate })} placeholder="09/30/2026" /><label className="block"><span className="mb-1 block text-xs font-bold text-[#48635a]">الأولوية</span><select value={doc.priority} onChange={e => patch({ priority: e.target.value })} className="h-10 w-full rounded-lg border border-input bg-background px-3"><option>عادي</option><option>مهم</option><option>عاجل</option></select></label></div><ItemTable doc={doc} patch={patch} addRow={addRow} purchase /><div className="grid gap-3 sm:grid-cols-2"><Field label="الإجمالي التقديري بالدينار" value={doc.totalDinar} onChange={totalDinar => patch({ totalDinar })} /><Field label="الإجمالي كتابةً" value={doc.totalInWords} onChange={totalInWords => patch({ totalInWords })} placeholder="اكتب المجموع بالحروف" /><Field label="شروط وملاحظات الطلب" value={doc.terms} onChange={terms => patch({ terms })} multiline placeholder="تفاصيل التوريد أو المواصفات المطلوبة" /><Field label="ملاحظات إضافية" value={doc.notes} onChange={notes => patch({ notes })} multiline /></div><div className="grid gap-4 border-t border-dashed border-[#c8a75a] pt-5 text-center sm:grid-cols-3"><div className="rounded-xl bg-[#f4f8f4] p-4"><b className="block text-sm">طالب الشراء</b><span className="mt-6 block border-b border-[#9bb5a8]" /></div><div className="rounded-xl bg-[#f4f8f4] p-4"><b className="block text-sm">اعتماد الإدارة</b><span className="mt-6 block border-b border-[#9bb5a8]" /></div><div className="rounded-xl bg-[#f4f8f4] p-4"><b className="block text-sm">الختم</b><span className="mt-6 block border-b border-[#9bb5a8]" /></div></div></div>; }
function VoucherForm({ type, doc, patch }: { type: "receipt" | "disbursement"; doc: FinancialDocument; patch: (changes: Partial<FinancialDocument>) => void }) { const isReceipt = type === "receipt"; return <div className="mt-6 space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="التاريخ" value={doc.date} onChange={date => patch({ date })} /><Field label="الرقم" value={doc.number} onChange={number => patch({ number })} /><Field label={isReceipt ? "اسم الدافع" : "اسم المستلم"} value={doc.personName} onChange={personName => patch({ personName })} /><Field label="المبلغ بالدينار" value={doc.amount} onChange={amount => patch({ amount })} /><Field label="المبلغ كتابةً" value={doc.amountText} onChange={amountText => patch({ amountText })} /><Field label="وذلك عن / سبب الدفع" value={doc.description} onChange={description => patch({ description })} /><label className="block"><span className="mb-1 block text-xs font-bold text-[#48635a]">طريقة الدفع</span><select value={doc.paymentMethod} onChange={e => patch({ paymentMethod: e.target.value as PaymentMethod })} className="h-10 w-full rounded-lg border px-3">{Object.entries(paymentLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><Field label="ملاحظات" value={doc.notes} onChange={notes => patch({ notes })} multiline /></div><div className="rounded-xl bg-[#f4f8f4] p-5 text-lg font-bold">{isReceipt ? "استلمنا من" : "صرفنا لـ"}: {doc.personName || "................"}<br /><span className="text-sm font-normal">المبلغ: {doc.amount || "0"} دينار · {paymentLabels[doc.paymentMethod]}</span></div></div>; }
