import { AccessGate, PlatformShell } from "@/components/PlatformShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useAuth } from "@/_core/hooks/useAuth";
import { useLanguage } from "@/lib/i18n";
import { trpc } from "@/lib/trpc";
import { Bell, Bot, CalendarDays, CheckCircle2, ChevronLeft, ClipboardList, Flower2, Leaf, Loader2, ScanSearch, Sparkles, Sprout, Trees, TriangleAlert } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

const statusClass: Record<string, string> = { active: "bg-[#edf5e4] text-[#4b7620]", planning: "bg-[#f6f1e6] text-[#92702d]", attention: "bg-[#fcefea] text-[#a3462d]", upcoming: "bg-[#edf5e4] text-[#4b7620]", draft: "bg-[#f6f1e6] text-[#92702d]", pendingReview: "bg-[#e9f0f8] text-[#386a96]", aiGenerated: "bg-[#edf0fb] text-[#546da2]", approved: "bg-[#e7f5e8] text-[#367646]", trial: "bg-[#eef4e7] text-[#4b7620]" };

export default function Dashboard() {
  const { language } = useLanguage(); const { user } = useAuth(); const snapshot = trpc.dashboard.snapshot.useQuery(); const growth = trpc.workspace.growth.list.useQuery(); const utils = trpc.useUtils();
  const [stage, setStage] = useState(""); const [health, setHealth] = useState<"good" | "monitor" | "attention">("good");
  const recordGrowth = trpc.workspace.growth.create.useMutation({ onSuccess: () => { toast.success(language === "ar" ? "تم حفظ سجل المتابعة" : "Growth record saved"); setStage(""); growth.refetch(); }, onError: error => toast.error(error.message) });
  const markRead = trpc.workspace.notification.markRead.useMutation({ onSuccess: () => { utils.dashboard.snapshot.invalidate(); }, onError: error => toast.error(error.message) });
  const data = snapshot.data; const isArabic = language === "ar";
  const cards = [{ icon: Trees, label: isArabic ? "المزارع والحدائق" : "Farms & gardens", value: (data?.farms.length || 0) + (data?.gardens.length || 0), href: "/projects", tone: "bg-[#eef4e7]" }, { icon: ClipboardList, label: isArabic ? "المشاريع والتصاميم" : "Projects & designs", value: (data?.projects.length || 0) + (data?.designs.length || 0), href: "/projects", tone: "bg-[#edf3ec]" }, { icon: ScanSearch, label: isArabic ? "تحليلات النبات" : "Plant analyses", value: data?.analyses.length ?? 0, href: "/diagnosis", tone: "bg-[#eff0e4]" }, { icon: Bell, label: isArabic ? "التنبيهات" : "Notifications", value: data?.notifications.filter(note => !note.readAt).length ?? 0, href: "#notifications", tone: "bg-[#f5f0e7]" }];
  const next = !(data?.farms.length || data?.gardens.length) ? { title: isArabic ? "أضف مزرعة أو حديقة" : "Add a farm or garden", text: isArabic ? "ابدأ بتسجيل موقعك الزراعي لربط المتابعة والتخطيط بالمكان الصحيح." : "Start by recording an agricultural site so planning and follow-up stay tied to the right place.", href: "/projects", action: isArabic ? "إضافة موقع" : "Add site" } : !data?.tasks.length ? { title: isArabic ? "أضف أول مهمة عناية" : "Add your first care task", text: isArabic ? "حوّل الملاحظة إلى نشاط متابع مع موعد ونوع عناية واضح." : "Turn an observation into a tracked activity with a clear care type and due date.", href: "/projects", action: isArabic ? "إضافة مهمة" : "Add task" } : { title: isArabic ? "حدّث سجل النمو" : "Update a growth record", text: isArabic ? "سجل مرحلة النمو أو المؤشرات التي تحتاج متابعة حتى يبقى القرار مرتبطًا بالواقع." : "Record growth stage or signals that need monitoring to keep decisions grounded in the field.", href: "#growth", action: isArabic ? "إضافة متابعة" : "Add check-in" };
  return <PlatformShell title={isArabic ? "لوحتي الزراعية" : "My agricultural workspace"} eyebrow={isArabic ? "نظرة مترابطة على مزرعتك وحديقتك ومشاريعك" : "A connected view of your farm, garden, and projects"}><AccessGate><main className="container py-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-xl font-bold text-[#314617]">{isArabic ? `أهلًا ${user?.name || "بك"}` : `Welcome, ${user?.name || "back"}`}</h2><p className="mt-1 text-sm text-[#6b785d]">{isArabic ? "هذه مساحة العمل التي تجمع سياقك وخطواتك القادمة." : "This is the workspace that connects your context and next steps."}</p></div><Link href="/profile" className="inline-flex items-center gap-2 text-sm font-bold text-[#52731f] no-underline">{isArabic ? "تحديث الملف الزراعي" : "Update agricultural profile"}<ChevronLeft className="size-4" /></Link></div>
  {snapshot.error && <div className="mt-5 rounded-xl border border-[#e9c5bd] bg-[#fff8f6] p-4 text-sm text-[#8c4a3c]">{isArabic ? "تعذر تحميل ملخص المساحة. أعد المحاولة بعد قليل." : "Your workspace summary could not load. Please try again shortly."}</div>}<section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(card => <Link href={card.href} key={card.label} className="rounded-2xl border border-[#35530e]/8 bg-white p-5 no-underline shadow-[0_8px_22px_rgba(48,67,22,.04)] transition hover:-translate-y-0.5"><div className="flex items-center justify-between"><span className={`grid size-10 place-items-center rounded-xl ${card.tone} text-[#35530e]`}><card.icon className="size-5" /></span><span className="text-2xl font-bold text-[#304314]">{snapshot.isLoading ? "—" : card.value}</span></div><p className="mt-4 text-sm font-semibold text-[#637154]">{card.label}</p></Link>)}</section>
  <section className="mt-7 grid gap-5 lg:grid-cols-[1.18fr_.82fr]"><div className="rounded-[1.5rem] border border-[#35530e]/8 bg-white p-5 shadow-[0_10px_28px_rgba(48,67,22,.04)] sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold tracking-[.14em] text-[#779248]">{isArabic ? "الخطوة التالية" : "NEXT BEST ACTION"}</p><h3 className="mt-2 text-xl font-bold text-[#314617]">{next.title}</h3></div><span className="grid size-10 place-items-center rounded-xl bg-[#edf5e4] text-[#35530e]"><Sparkles className="size-5" /></span></div><p className="mt-3 max-w-lg text-sm leading-6 text-[#6b785d]">{next.text}</p><Button asChild className="mt-5 rounded-xl bg-[#35530e] text-white hover:bg-[#294108]"><Link href={next.href}>{next.action}</Link></Button></div><div className="rounded-[1.5rem] border border-[#35530e]/8 bg-white p-5 shadow-[0_10px_28px_rgba(48,67,22,.04)] sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#f4efe2] text-[#7b662a]"><CalendarDays className="size-5" /></span><div><p className="text-xs font-bold tracking-[.14em] text-[#7b8d69]">{isArabic ? "تقويم العناية" : "CARE CALENDAR"}</p><h3 className="mt-1 font-bold text-[#314617]">{isArabic ? "مهام قادمة" : "Upcoming tasks"}</h3></div></div>{data?.tasks.length ? <div className="mt-4 space-y-2">{data.tasks.slice(0, 3).map(task => <div key={task.id} className="flex items-center justify-between rounded-xl bg-[#f8f9f5] px-3 py-2.5"><span className="text-sm font-semibold text-[#536146]">{task.title}</span><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${statusClass[task.status] || statusClass.upcoming}`}>{task.status}</span></div>)}</div> : <div className="mt-4 rounded-xl border border-dashed border-[#35530e]/15 px-4 py-5 text-center text-sm leading-6 text-[#728064]">{isArabic ? "لا توجد مهام بعد. أضف مزرعة أو حديقة لإنشاء خطة عناية." : "No tasks yet. Add a farm or garden to create a care plan."}</div>}</div></section>
  <section id="growth" className="mt-7 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><GrowthCard isArabic={isArabic} stage={stage} setStage={setStage} health={health} setHealth={setHealth} saving={recordGrowth.isPending} save={(event) => { event.preventDefault(); recordGrowth.mutate({ assetType: "plant", growthStage: stage || undefined, healthStatus: health }); }} /><section className="rounded-[1.5rem] border border-[#35530e]/8 bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#eff4e9] text-[#35530e]"><Leaf className="size-5" /></span><div><p className="text-xs font-bold tracking-[.14em] text-[#779248]">{isArabic ? "سجل النمو" : "GROWTH RECORD"}</p><h3 className="mt-1 text-xl font-bold text-[#314617]">{isArabic ? "آخر المتابعات" : "Recent check-ins"}</h3></div></div><div className="mt-5 space-y-2">{growth.data?.slice(0, 4).map(record => <div key={record.id} className="flex items-center justify-between gap-3 rounded-xl bg-[#f8f9f5] px-3 py-3"><div><strong className="block text-sm text-[#44572c]">{record.growthStage || (isArabic ? "متابعة ميدانية" : "Field check-in")}</strong><span className="text-xs text-[#778668]">{new Date(record.recordedAt).toLocaleDateString(isArabic ? "ar" : "en")}</span></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${record.healthStatus === "attention" ? "bg-[#fcefea] text-[#a3462d]" : record.healthStatus === "monitor" ? "bg-[#fff7e9] text-[#9a6d29]" : "bg-[#edf5e4] text-[#4b7620]"}`}>{record.healthStatus}</span></div>)}{!growth.isLoading && !growth.data?.length && <p className="rounded-xl border border-dashed border-[#c3d4ae] p-5 text-center text-sm text-[#718062]">{isArabic ? "أضف أول متابعة ميدانية لتظهر هنا." : "Add a first field check-in to see it here."}</p>}</div></section></section>
  <section id="notifications" className="mt-7 grid gap-5 lg:grid-cols-2"><section className="rounded-[1.5rem] border border-[#35530e]/8 bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><Bell className="size-5 text-[#648534]" /><h3 className="text-xl font-bold text-[#314617]">{isArabic ? "التنبيهات والمتابعة" : "Notifications & follow-up"}</h3></div><div className="mt-4 space-y-2">{data?.notifications.map(note => <button key={note.id} onClick={() => !note.readAt && markRead.mutate({ notificationId: note.id })} className={`w-full rounded-xl p-3 text-start ${note.readAt ? "bg-[#f8f9f5]" : "bg-[#eff5e7]"}`}><strong className="block text-sm text-[#405525]">{note.title}</strong><span className="mt-1 block text-xs leading-5 text-[#6f7e60]">{note.body}</span></button>)}{!data?.notifications.length && <p className="rounded-xl border border-dashed border-[#c3d4ae] p-5 text-center text-sm text-[#718062]">{isArabic ? "ستظهر هنا تنبيهات المشاريع والمراجعات والمهام." : "Project, review, and task notifications will appear here."}</p>}</div></section><section className="rounded-[1.5rem] border border-[#35530e]/8 bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><CheckCircle2 className="size-5 text-[#648534]" /><h3 className="text-xl font-bold text-[#314617]">{isArabic ? "الاشتراك والطلبات" : "Subscription & orders"}</h3></div><div className="mt-4 rounded-xl bg-[#f8f9f5] p-4"><p className="text-sm font-bold text-[#41552a]">{data?.subscription ? `${data.subscription.planCode} · ${data.subscription.status}` : (isArabic ? "لا يوجد اشتراك نشط" : "No active subscription")}</p><p className="mt-2 text-sm leading-6 text-[#718062]">{isArabic ? "يمكنك إتمام طلبات المتجر من السلة، وتتم معلومات الدفع وتأكيد الطلب في صفحة المتجر الآمنة." : "You can complete store purchases from the cart; payment information and order confirmation remain on the secure storefront page."}</p><Link href="/shop" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-[#52731f] no-underline">{isArabic ? "الذهاب إلى المتجر" : "Go to store"}<ChevronLeft className="size-4" /></Link></div>{data?.designs.length ? <div className="mt-3 rounded-xl border border-[#dde9cf] p-3 text-sm text-[#617150]"><span className="font-bold">{data.designs.length}</span> {isArabic ? "مسودة/مخرج تصميم مرتبط بمشاريعك." : "design draft/output linked to your projects."}</div> : null}</section></section><TaskCalendar tasks={data?.tasks || []} isArabic={isArabic} />
  <section className="mt-7 rounded-[1.5rem] border border-[#35530e]/8 bg-white p-5 shadow-[0_10px_28px_rgba(48,67,22,.04)] sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-bold tracking-[.14em] text-[#779248]">{isArabic ? "إجراءات سريعة" : "QUICK ACTIONS"}</p><h3 className="mt-1 text-xl font-bold text-[#314617]">{isArabic ? "إلى أين تريد أن تبدأ؟" : "Where would you like to start?"}</h3></div><Leaf className="size-6 text-[#829f4d]" /></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ icon: Bot, href: "/engineer", label: isArabic ? "اسأل المهندس الذكي" : "Ask the AI engineer" }, { icon: ScanSearch, href: "/diagnosis", label: isArabic ? "حلّل صورة نبات" : "Analyze plant image" }, { icon: Sprout, href: "/selector", label: isArabic ? "ماذا أزرع؟" : "What should I grow?" }, { icon: ClipboardList, href: "/projects", label: isArabic ? "اطلب تصميمًا" : "Request a design" }].map(action => <Link href={action.href} key={action.href} className="flex items-center gap-3 rounded-xl bg-[#f7f9f3] p-4 text-sm font-bold text-[#3d5222] no-underline transition hover:bg-[#edf4e4]"><action.icon className="size-5 text-[#5d8030]" />{action.label}</Link>)}</div></section>
  </main></AccessGate></PlatformShell>;
}

function GrowthCard({ isArabic, stage, setStage, health, setHealth, saving, save }: { isArabic: boolean; stage: string; setStage: (value: string) => void; health: "good" | "monitor" | "attention"; setHealth: (value: "good" | "monitor" | "attention") => void; saving: boolean; save: (event: FormEvent) => void }) { return <section className="rounded-[1.5rem] bg-[#35530e] p-5 text-white sm:p-6"><TriangleAlert className="size-5 text-[#d8e9b7]" /><h3 className="mt-4 text-xl font-bold">{isArabic ? "متابعة ميدانية سريعة" : "Quick field check-in"}</h3><p className="mt-2 text-sm leading-6 text-[#dce8cb]">{isArabic ? "سجل مؤشرًا مختصرًا. عند ظهور تدهور شديد أو انتشار سريع، استخدم تحليل النبات واطلب مختصًا." : "Record a concise signal. For severe decline or rapid spread, use plant analysis and request a specialist."}</p><form onSubmit={save} className="mt-5 space-y-3"><Input value={stage} onChange={event => setStage(event.target.value)} className="h-10 rounded-xl border-0 bg-white/95 text-[#344b18]" placeholder={isArabic ? "مرحلة النمو أو الملاحظة" : "Growth stage or observation"} /><Select value={health} onValueChange={value => setHealth(value as typeof health)}><SelectTrigger className="h-10 rounded-xl border-0 bg-white/95 text-[#344b18]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="good">{isArabic ? "مستقر" : "Stable"}</SelectItem><SelectItem value="monitor">{isArabic ? "يحتاج متابعة" : "Monitor"}</SelectItem><SelectItem value="attention">{isArabic ? "يحتاج انتباهًا" : "Needs attention"}</SelectItem></SelectContent></Select><Button type="submit" disabled={saving} className="h-10 w-full rounded-xl bg-white text-[#35530e] hover:bg-[#edf4e5]">{saving ? <Loader2 className="size-4 animate-spin" /> : <CheckCircle2 className="size-4" />}{isArabic ? "حفظ المتابعة" : "Save check-in"}</Button></form></section>; }
function TaskCalendar({ tasks, isArabic }: { tasks: Array<{ id: number; title: string; dueAt: Date | null; status: string }>; isArabic: boolean }) { const days = Array.from({ length: 14 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() + index); return date; }); return <section className="mt-7 rounded-[1.5rem] border border-[#35530e]/8 bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><CalendarDays className="size-5 text-[#648534]" /><div><p className="text-xs font-bold tracking-[.14em] text-[#779248]">{isArabic ? "تقويم العناية" : "CARE CALENDAR"}</p><h3 className="mt-1 text-xl font-bold text-[#314617]">{isArabic ? "أربعة عشر يومًا قادمة" : "Next fourteen days"}</h3></div></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7">{days.map(day => { const key = day.toDateString(); const todayTasks = tasks.filter(task => task.dueAt && new Date(task.dueAt).toDateString() === key); return <div key={key} className="min-h-24 rounded-xl bg-[#f7f9f4] p-3"><time className="block text-xs font-bold text-[#54702f]">{day.toLocaleDateString(isArabic ? "ar" : "en", { weekday: "short", day: "numeric" })}</time>{todayTasks.slice(0, 2).map(task => <p key={task.id} className="mt-2 rounded-md bg-white px-2 py-1 text-[10px] leading-4 text-[#536746]">{task.title}</p>)}{!todayTasks.length && <span className="mt-4 block text-[10px] text-[#a2ad94]">{isArabic ? "لا مهام" : "No tasks"}</span>}</div>; })}</div></section>; }
