import { useAuth } from "@/_core/hooks/useAuth";
import { PlatformShell } from "@/components/PlatformShell";
import { useLanguage } from "@/lib/i18n";
import { ArrowLeft, ArrowRight, Bot, CheckCircle2, ClipboardCheck, Droplets, Gauge, Leaf, LineChart, ScanSearch, ShieldCheck, Sprout, SunMedium, TreePine, Waves } from "lucide-react";
import { Link, useLocation } from "wouter";
import { Button } from "@/components/ui/button";

const heroImage = "/manus-storage/al-qadri-smart-agriculture-hero_28e6f928.jpg";

export default function Home() {
  const { language, t } = useLanguage();
  const { isAuthenticated } = useAuth();
  const [, setLocation] = useLocation();
  const Arrow = language === "ar" ? ArrowLeft : ArrowRight;
  const steps = [
    { icon: Bot, ar: "اسأل", en: "Ask" }, { icon: ScanSearch, ar: "حلّل", en: "Analyze" }, { icon: Sprout, ar: "خطّط", en: "Plan" }, { icon: ClipboardCheck, ar: "راجع", en: "Review" }, { icon: LineChart, ar: "تابع", en: "Follow up" },
  ];
  const services = [
    { icon: Bot, title: language === "ar" ? "المهندس الزراعي الذكي" : "AI agricultural engineer", text: language === "ar" ? "إرشاد سياقي يراعي موقعك ومياهك وتربتك وأهدافك." : "Context-aware guidance shaped by your place, water, soil, and goals.", href: "/engineer", tone: "bg-[#eff5e7]" },
    { icon: ScanSearch, title: language === "ar" ? "حلّل نباتك" : "Analyze a plant", text: language === "ar" ? "ارفع صورة لتحصل على قراءة أولية حذرة وخطوات آمنة." : "Upload a photo for cautious initial triage and safe next steps.", href: "/diagnosis", tone: "bg-[#f6f1e6]" },
    { icon: Sprout, title: language === "ar" ? "ماذا أزرع؟" : "What should I grow?", text: language === "ar" ? "ترشيحات قابلة للتفسير قبل بدء التخطيط أو التنفيذ." : "Explainable suitability recommendations before you plan or build.", href: "/selector", tone: "bg-[#edf3ee]" },
    { icon: TreePine, title: language === "ar" ? "تابع مزرعتك وحديقتك" : "Manage farms & gardens", text: language === "ar" ? "مهام العناية والمشاريع والسجل الزراعي في مساحة واحدة." : "Care tasks, projects, and your agricultural record in one workspace.", href: "/dashboard", tone: "bg-[#edf0df]" },
  ];

  return <PlatformShell>
    <main>
      <section className="relative overflow-hidden border-b border-[#35530e]/10 bg-[#eff3e8]">
        <div className="absolute inset-0 opacity-60" style={{ backgroundImage: "radial-gradient(circle at 10% 15%, rgba(255,255,255,.95) 0, transparent 28%), linear-gradient(115deg, rgba(247,250,242,.92), rgba(234,242,225,.18))" }} />
        <div className="container relative grid min-h-[610px] items-center gap-10 py-12 lg:grid-cols-[.92fr_1.08fr] lg:py-16">
          <div className="order-2 max-w-2xl lg:order-1">
            <div className="inline-flex items-center gap-2 rounded-full border border-[#5d7d30]/18 bg-white/80 px-3 py-1.5 text-xs font-bold text-[#476b19]"><span className="size-1.5 rounded-full bg-[#88a849]" />{language === "ar" ? "ذكاء زراعي مسؤول، بتوجيه من الخبرة" : "Responsible AI, guided by agricultural expertise"}</div>
            <h1 className="mt-6 text-balance text-4xl font-bold leading-[1.16] tracking-tight text-[#29410d] sm:text-5xl lg:text-6xl">{language === "ar" ? "مهندس زراعي ذكي بين يديك." : "An intelligent agricultural engineer at your fingertips."}</h1>
            <p className="mt-6 max-w-xl text-lg leading-8 text-[#607052]">{language === "ar" ? "من الاستشارة والتشخيص إلى التخطيط والمتابعة، يساعدك القادري الزراعي الذكي في اتخاذ قرارات أوضح لحديقتك أو مزرعتك — بذكاء سياقي ومراجعة خبراء عند الحاجة." : "From consultation and diagnosis to planning and follow-up, Al-Qadri helps you make clearer decisions for your garden or farm—with contextual intelligence and expert review when needed."}</p>
            <div className="mt-8 flex flex-wrap gap-3"><Button asChild className="h-12 rounded-xl bg-[#35530e] px-5 text-base text-white shadow-[0_12px_24px_rgba(53,83,14,.22)] hover:bg-[#294108]"><Link href={isAuthenticated ? "/dashboard" : "/selector"}>{t.start}<Arrow className="ms-2 size-4" /></Link></Button>{!isAuthenticated && <Button onClick={() => setLocation("/auth")} variant="outline" className="h-12 rounded-xl border-[#35530e]/20 bg-white px-5 text-base text-[#35530e] hover:bg-[#f4f7f0]">{t.signIn}</Button>}</div>
            <div className="mt-10 flex flex-wrap gap-x-5 gap-y-3 text-sm font-semibold text-[#5d6b4d]"><span className="flex items-center gap-2"><ShieldCheck className="size-4 text-[#66852e]" />{language === "ar" ? "توصيات حذرة" : "Cautious guidance"}</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[#66852e]" />{language === "ar" ? "خطوات قابلة للتفسير" : "Explainable next steps"}</span></div>
          </div>
          <div className="order-1 lg:order-2"><div className="relative mx-auto max-w-[720px]"><div className="absolute -inset-4 rounded-[2.25rem] bg-[#6c8b37]/15 blur-2xl" /><div className="relative aspect-[16/11] w-full overflow-hidden rounded-[2rem] border border-[#35530e]/10 bg-gradient-to-br from-[#f9fbf3] via-[#edf4df] to-[#dce9c3] shadow-[0_24px_60px_rgba(42,62,18,.18)]"><div className="absolute -end-10 -top-12 size-48 rounded-full bg-white/55 blur-2xl" /><div className="absolute -bottom-20 -start-12 size-56 rounded-full bg-[#b4ce65]/35 blur-3xl" /><span className="absolute start-[12%] top-[14%] grid size-10 place-items-center rounded-2xl border border-white/80 bg-white/80 text-[#6c8b2a] shadow-sm"><SunMedium className="size-5" /></span><span className="absolute end-[14%] top-[24%] grid size-11 place-items-center rounded-2xl border border-white/80 bg-white/80 text-[#4e8b9a] shadow-sm"><Droplets className="size-5" /></span><span className="absolute end-[19%] bottom-[22%] grid size-10 place-items-center rounded-2xl border border-white/80 bg-white/80 text-[#78923a] shadow-sm"><Gauge className="size-5" /></span><img src="/assets/tractor.png" alt={language === "ar" ? "حديقة زراعية مع نافورة وأشجار" : "Agricultural park with a fountain and trees"} className="absolute bottom-[7%] left-1/2 h-[64%] w-auto max-w-[70%] -translate-x-1/2 object-contain drop-shadow-[0_18px_12px_rgba(53,83,14,.2)]" /><div className="absolute bottom-3 start-3 max-w-[190px] rounded-xl border border-white/70 bg-white/90 p-2.5 shadow-lg backdrop-blur"><div className="flex items-center gap-1.5 text-[11px] font-bold text-[#35530e]"><Waves className="size-3.5" />{language === "ar" ? "مزرعة أذكى، بحجم أخف" : "A lighter, smarter farm visual"}</div></div></div></div></div>
        </div>
      </section>

      <section className="container py-12 sm:py-16"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-[.16em] text-[#759244]">{language === "ar" ? "رحلة مترابطة" : "A CONNECTED JOURNEY"}</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-[#293d12]">{language === "ar" ? "من الملاحظة إلى متابعة ذات معنى" : "From observation to meaningful follow-up"}</h2></div><p className="max-w-md text-sm leading-6 text-[#68775a]">{language === "ar" ? "ليست خدمات منفصلة؛ كل خطوة تحفظ سياقك وتفتح ما بعدها." : "These are not disconnected tools; every step preserves context and unlocks the next."}</p></div><div className="mt-9 grid grid-cols-5 gap-2 sm:gap-4">{steps.map((step, index) => <div key={step.ar} className="relative text-center">{index < steps.length - 1 && <span className="absolute top-5 start-[61%] hidden h-px w-[78%] bg-[#cfdcc0] md:block" />}<span className="relative mx-auto grid size-10 place-items-center rounded-xl bg-[#e9f0df] text-[#35530e] sm:size-12"><step.icon className="size-4 sm:size-5" /></span><p className="mt-2 text-xs font-bold text-[#4d5d3b]">{language === "ar" ? step.ar : step.en}</p></div>)}</div></section>

      <section className="border-y border-[#35530e]/8 bg-white"><div className="container py-14 sm:py-20"><div className="max-w-2xl"><p className="text-xs font-bold tracking-[.16em] text-[#759244]">{language === "ar" ? "خدمات موجهة بالفعل" : "PURPOSEFUL SERVICES"}</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-[#293d12] sm:text-4xl">{language === "ar" ? "كل ما تحتاجه لاتخاذ قرار زراعي أفضل" : "Everything needed for a better agricultural decision"}</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2">{services.map(service => <Link key={service.href} href={service.href} className="group rounded-[1.5rem] border border-[#35530e]/8 bg-white p-5 no-underline shadow-[0_10px_30px_rgba(48,67,22,.05)] transition duration-200 hover:-translate-y-1 hover:shadow-[0_16px_38px_rgba(48,67,22,.1)]"><span className={`grid size-11 place-items-center rounded-xl ${service.tone} text-[#35530e]`}><service.icon className="size-5" /></span><h3 className="mt-5 text-lg font-bold text-[#314617]">{service.title}</h3><p className="mt-2 text-sm leading-6 text-[#68775a]">{service.text}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-[#52731f]">{language === "ar" ? "اكتشف الخدمة" : "Explore service"}<Arrow className="size-4 transition-transform group-hover:-translate-x-1 rtl:group-hover:translate-x-1" /></span></Link>)}</div></div></section>
      <section className="container py-16"><div className="grid gap-6 rounded-[2rem] bg-[#35530e] p-7 text-white shadow-[0_20px_50px_rgba(53,83,14,.2)] sm:p-10 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div><p className="text-xs font-bold tracking-[.16em] text-[#d5e5b8]">{language === "ar" ? "الرعاية أولاً" : "SAFETY FIRST"}</p><h2 className="mt-3 text-3xl font-bold leading-tight">{language === "ar" ? "الذكاء يساند القرار؛ والخبرة تراجع ما يستحق المراجعة." : "Intelligence supports decisions; expertise reviews what deserves review."}</h2><p className="mt-4 max-w-xl leading-7 text-[#e1ebd0]">{language === "ar" ? "نوضح حدود التوصية، نجمع البيانات الناقصة، ونصعّد الحالات الحساسة أو الحرجة إلى المختصين." : "We explain recommendation limits, collect missing data, and escalate sensitive or critical cases to specialists."}</p></div><div className="flex justify-start lg:justify-end"><Button asChild className="h-12 rounded-xl bg-white px-5 text-[#35530e] hover:bg-[#eef5e4]"><Link href="/knowledge">{language === "ar" ? "استكشف قاعدة المعرفة" : "Explore knowledge hub"}<Arrow className="ms-2 size-4" /></Link></Button></div></div></section>
    </main>
  </PlatformShell>;
}
