export type TreeKnowledge = {
  category: "tree";
  nameAr: string;
  nameEn: string;
  scientificName: string;
  summaryAr: string;
  summaryEn: string;
  growingData: {
    countries: string[];
    planting: string;
    care: string;
    water: string;
    light: string;
    diseases: string[];
    pests: string[];
    control: string;
    sources: { label: string; url: string }[];
  };
};

const faoCalendar = { label: "FAO Crop Calendar", url: "https://cropcalendar.apps.fao.org/" };
const plantwise = { label: "CABI PlantwisePlus", url: "https://plantwiseplusknowledgebank.org/" };
const faoWater = { label: "FAO Irrigation and Drainage 56", url: "https://www.fao.org/4/x0490e/x0490e00.htm" };
const icarda = { label: "ICARDA", url: "https://icarda.org/" };
const acsad = { label: "ACSAD Date Palm Program", url: "https://acsad.org/en/مشروع-تطوير-عمليات-خدمة-بساتين-النخيل-2/" };

export const baseKnowledge: TreeKnowledge[] = [
  { category: "tree", nameAr: "الزيتون", nameEn: "Olive", scientificName: "Olea europaea", summaryAr: "شجرة متوسطية معمرة مناسبة لعدد كبير من البيئات، ويحدد نجاحها الصنف والصرف والملوحة واحتياج البرودة والإدارة.", summaryEn: "A long-lived Mediterranean tree suited to many environments; success depends on cultivar, drainage, salinity, chilling needs, and management.", growingData: { countries: ["الأردن", "فلسطين", "مصر", "السعودية", "قطر"], planting: "تزرع الشتلات غالبًا من أواخر الخريف إلى نهاية الشتاء بعد انحسار موجات الصقيع؛ في المناطق الدافئة يمكن التوسع في الموسم مع توفر الري.", care: "اختر شتلة سليمة مطعمة، اترك مسافة مناسبة للصنف، حسّن الصرف، شكّل الهيكل تدريجيًا، ونفذ تقليمًا خفيفًا بعد معرفة الحمل. افحص ملوحة الماء والتربة دوريًا.", water: "منخفض إلى متوسط بعد التأسيس؛ يرتفع في أول عامين وأثناء العقد وتضخم الثمار.", light: "شمس كاملة", diseases: ["ذبول الفرتيسيليوم", "عين الطاووس", "تبقعات الأوراق", "تعفن الجذور عند سوء الصرف"], pests: ["ذبابة الزيتون", "الحشرة القطنية", "الحشرات القشرية", "حفار الأغصان"], control: "ابدأ بالصرف والتهوية وإزالة الأجزاء المصابة والنظافة الزراعية والمراقبة بالمصائد. لا تستخدم مبيدًا إلا بعد تحديد الآفة والرجوع إلى تسجيلات بلدك وفترة الأمان.", sources: [faoCalendar, plantwise, faoWater] } },
  { category: "tree", nameAr: "نخيل التمر", nameEn: "Date palm", scientificName: "Phoenix dactylifera", summaryAr: "شجرة محبة للحرارة والضوء، وتنجح في البيئات الصحراوية عند ضبط الملوحة والصرف والتلقيح والخدمة الموسمية.", summaryEn: "A heat- and light-loving tree that performs in desert climates when salinity, drainage, pollination, and seasonal care are managed.", growingData: { countries: ["الأردن", "فلسطين", "مصر", "السعودية", "قطر"], planting: "تزرع الفسائل أو الشتلات النسيجية في الأجواء المعتدلة غالبًا من الخريف إلى الربيع، مع تجنب الحر الشديد والصقيع ومراعاة مصدر إكثار موثوق.", care: "استخدم فسيلة أو شتلة معتمدة وخالية من الإصابة، اضبط الري والصرف، نظف السعف الجاف، نفذ التلقيح في موعده، وخفف العذوق حسب الصنف والحمل.", water: "متوسط إلى مرتفع حسب العمر والتربة والحرارة والملوحة؛ لا يعني تحمل الحرارة تحمل التغدق.", light: "شمس كاملة", diseases: ["اللفحة السوداء", "تبقعات الأوراق", "البيوض في مناطق الخطر", "تعفن القلب والجذور"], pests: ["سوسة النخيل الحمراء", "حشرة النخيل القشرية", "حفار العذوق", "دوباس النخيل"], control: "افحص الجذع والفسائل دوريًا، امنع نقل مواد نباتية مجهولة، اعزل الحالات المشتبه بها واتبع برنامج وزارة الزراعة والمكافحة المتكاملة؛ البيوض لا يعالج منزليًا ويحتاج تبليغًا وفحصًا مخبريًا.", sources: [acsad, plantwise, icarda] } },
  { category: "tree", nameAr: "الحمضيات: البرتقال والليمون", nameEn: "Citrus: orange and lemon", scientificName: "Citrus spp.", summaryAr: "مجموعة أشجار دائمة الخضرة تحتاج شمسًا وصرفًا جيدًا وحماية من الصقيع والملوحة، وتختلف الأصناف في تحملها وموعد حملها.", summaryEn: "Evergreen trees needing sun, good drainage, and protection from frost and salinity; cultivars differ in tolerance and bearing time.", growingData: { countries: ["الأردن", "فلسطين", "مصر", "السعودية", "قطر"], planting: "تزرع الشتلات المطعمة من الخريف إلى الربيع في المناطق المعتدلة، أو في نافذة الشتاء بالمناطق الحارة، مع تجنب أيام الصقيع والحر الشديد.", care: "اختر أصلًا وصنفًا مناسبين، لا تدفن منطقة التطعيم، حافظ على دائرة خالية من الحشائش، قلّم فقط لإزالة الجاف والمتزاحم، وراقب الملوحة والحديد والعناصر الصغرى.", water: "متوسط إلى مرتفع؛ انتظام الرطوبة مهم مع تجنب ركود الماء.", light: "شمس كاملة", diseases: ["التصمغ وتعفن الجذور", "التقرح البكتيري", "العفن البني", "الاصفرار المرتبط بسوء التغذية أو الجذور"], pests: ["حفار أوراق الحمضيات", "الذبابة البيضاء", "الحشرات القشرية", "البق الدقيقي", "ذباب الفاكهة"], control: "استخدم شتلات سليمة، حسّن الصرف والتهوية، أزل الأوراق أو الأفرع الميتة، راقب المصائد، وحافظ على الأعداء الحيوية. قرار المبيد يعتمد على التشخيص والملصق الرسمي في الدولة.", sources: [faoCalendar, plantwise, faoWater] } },
  { category: "tree", nameAr: "الرمان", nameEn: "Pomegranate", scientificName: "Punica granatum", summaryAr: "شجرة أو شجيرة مثمرة تتحمل الجفاف نسبيًا بعد التأسيس، وتحتاج شمسًا وصرفًا جيدًا وتنظيم حملها لتقليل تشقق الثمار.", summaryEn: "A fruit tree or shrub relatively tolerant of drought after establishment; it needs sun, drainage, and crop-load management to reduce fruit cracking.", growingData: { countries: ["الأردن", "فلسطين", "مصر", "السعودية", "قطر"], planting: "تزرع الشتلات الساكنة من أواخر الخريف إلى أواخر الشتاء، وتؤجل في مناطق الصقيع حتى زوال الخطر؛ الشتلات المزروعة في أصص تحتاج تدرجًا في النقل.", care: "اختر مكانًا مشمسًا، شكّلها على ساق أو عدة سيقان حسب الهدف، أزل السرطانات، حافظ على رطوبة مستقرة أثناء تكوين الثمار، واجمع الثمار في موعدها.", water: "منخفض إلى متوسط بعد التأسيس، مع أهمية الانتظام في الإزهار وتضخم الثمار.", light: "شمس كاملة", diseases: ["تبقعات الأوراق", "أعفان الثمار", "تعفن الجذور", "لفحات الأفرع"], pests: ["فراشة الرمان", "ذباب الفاكهة", "البق الدقيقي", "الحشرات القشرية"], control: "نظافة البستان، إزالة الثمار المتساقطة والمتحللة، تقليم الأفرع المصابة، تحسين التهوية، والمراقبة بالمصائد؛ تجنب الرش العشوائي وقت نشاط النحل.", sources: [faoCalendar, plantwise] } },
  { category: "tree", nameAr: "التين", nameEn: "Fig", scientificName: "Ficus carica", summaryAr: "شجرة متساقطة الأوراق مناسبة للمناخ المتوسطي والدافئ، وتنجح مع الصرف والشمس وتنظيم الري أثناء نضج الثمار.", summaryEn: "A deciduous tree suited to Mediterranean and warm climates, performing with drainage, sun, and managed irrigation during fruit ripening.", growingData: { countries: ["الأردن", "فلسطين", "مصر", "السعودية", "قطر"], planting: "تزرع الشتلات العارية الجذور في الشتاء أثناء السكون، وشتلات الأصص في الموسم المعتدل مع حماية الجذور من الحر والصقيع.", care: "اترك مساحة للنمو، شكّل هيكلًا مفتوحًا، أزل السرطانات والأفرع المتقاطعة، حافظ على تغطية عضوية دون ملامسة الجذع، واضبط الري لتقليل تشقق الثمار.", water: "منخفض إلى متوسط؛ يزيد مع الحرارة وحجم الشجرة والحمل.", light: "شمس كاملة", diseases: ["صدأ التين", "أعفان الجذور", "مومياء الثمار", "تبقعات الأوراق"], pests: ["ذبابة الفاكهة", "حفارات الساق", "البق الدقيقي", "الطيور والدبابير عند النضج"], control: "أزل الثمار المصابة والمتساقطة، حافظ على النظافة والتهوية، استخدم شبكًا أو مصائد عند الحاجة، ولا تعالج عرضًا دون فحص سببه.", sources: [faoCalendar, plantwise] } },
  { category: "tree", nameAr: "العنب", nameEn: "Grapevine", scientificName: "Vitis vinifera", summaryAr: "كرمة معمرة تحتاج شمسًا وتربية وتقليمًا دقيقين؛ تختلف مواعيدها بين المرتفعات والوادي والبيئات الحارة المحمية.", summaryEn: "A perennial vine requiring sun, training, and precise pruning; timing differs between highlands, valleys, and hot protected environments.", growingData: { countries: ["الأردن", "فلسطين", "مصر", "السعودية", "قطر"], planting: "تزرع الكروم العارية الجذور في الشتاء أثناء السكون، وتزرع شتلات الأصص في الموسم المعتدل مع تثبيت الري بعد النقل.", care: "جهز تعريشة قوية، نفذ التقليم الشتوي حسب الصنف، نظم الحمل والتهوية، أبعد العناقيد عن البلل المستمر، وراقب الملوحة والحرارة.", water: "متوسط؛ يرتفع في التزهير والعقد وتضخم الحبة وينخفض قرب النضج وفق الصنف والتربة.", light: "شمس كاملة", diseases: ["البياض الدقيقي", "البياض الزغبي", "العفن الرمادي", "أمراض الخشب"], pests: ["فراشة ثمار العنب", "البق الدقيقي", "العناكب", "التربس"], control: "التقليم والتهوية وإزالة الأجزاء المصابة وإدارة الرطوبة أولًا، مع برنامج وقائي محلي عند الضرورة وفترة أمان واضحة قبل الحصاد.", sources: [faoCalendar, plantwise, faoWater] } },
  { category: "tree", nameAr: "اللوز", nameEn: "Almond", scientificName: "Prunus dulcis", summaryAr: "شجرة متساقطة تحتاج شتاءً باردًا نسبيًا للإزهار المنتظم، وتتعرض أزهارها لخطر الصقيع الربيعي.", summaryEn: "A deciduous tree needing some winter chill for regular flowering, with blossoms vulnerable to spring frost.", growingData: { countries: ["الأردن", "فلسطين", "مصر", "السعودية"], planting: "تزرع الشتلات في الشتاء أثناء السكون، ويختار الصنف حسب ساعات البرودة وخطر الصقيع في الموقع؛ نجاحها في المناطق الحارة جدًا محدود دون صنف مناسب.", care: "اختر أصلًا وصنفًا متوافقين، وفر ملقحًا عند الحاجة، شكّل شجرة مفتوحة، راقب الإزهار والصقيع، واضبط الري والتغذية دون إفراط نيتروجين.", water: "متوسط؛ حساس للجفاف أثناء الإزهار وتكوين الثمرة، وحساس للتغدق.", light: "شمس كاملة", diseases: ["التصمغ", "العفن البني", "تبقعات الأوراق", "تعفن الجذور"], pests: ["حفارات الأفرع", "المنّ", "العناكب", "دودة ثمار اللوز"], control: "استخدم شتلات سليمة، أزل الأفرع المصابة، حافظ على تقليم وتهوية مناسبين، وطبّق المكافحة المتكاملة وفق الرصد المحلي.", sources: [faoCalendar, plantwise, icarda] } },
  { category: "tree", nameAr: "المشمش والخوخ", nameEn: "Apricot and peach", scientificName: "Prunus armeniaca / Prunus persica", summaryAr: "أشجار حجرية تحتاج أصنافًا متوافقة مع برودة الموقع، وتحتاج إدارة دقيقة للتقليم والري والأمراض خلال الإزهار والثمار.", summaryEn: "Stone fruits needing cultivars matched to local chill; pruning, irrigation, and disease management are important during flowering and fruiting.", growingData: { countries: ["الأردن", "فلسطين", "مصر", "السعودية"], planting: "تزرع الشتلات الساكنة في الشتاء، مع اختيار صنف قليل البرودة للمناطق الدافئة وصنف أعلى البرودة للمناطق المرتفعة.", care: "شكّل هيكلًا مفتوحًا، خفف الثمار عند الحاجة، نظّم الري، أزل الثمار المحنطة، وراقب الإزهار المبكر والصقيع.", water: "متوسط؛ انتظام الري مهم، والتذبذب الشديد يرفع مشاكل الثمار.", light: "شمس كاملة", diseases: ["العفن البني", "التنقير البكتيري", "تجعد أوراق الخوخ", "التصمغ"], pests: ["دودة ثمار الخوخ", "المنّ", "الحشرات القشرية", "حفارات الساق"], control: "النظافة والتقليم والتهوية وإزالة الأجزاء المصابة، مع استخدام أصناف وأصول سليمة والرجوع لتوصيات الدولة قبل أي معاملة.", sources: [faoCalendar, plantwise] } },
  { category: "tree", nameAr: "المانجو", nameEn: "Mango", scientificName: "Mangifera indica", summaryAr: "شجرة شبه استوائية مناسبة للمناطق الدافئة الخالية من الصقيع؛ تحتاج مساحة وشمسًا وإدارة للماء والملوحة.", summaryEn: "A subtropical tree suited to warm frost-free sites, needing space, sun, and careful water and salinity management.", growingData: { countries: ["مصر", "السعودية", "قطر", "فلسطين"], planting: "تزرع الشتلات المطعمة في الربيع أو بداية الموسم الدافئ بعد زوال البرد، مع حماية الشتلة من الرياح والحر الشديد في الأسابيع الأولى.", care: "اختر صنفًا وأصلًا مناسبين، وفر صرفًا ممتازًا، شكّل الشجرة تدريجيًا، تجنب الإفراط في التسميد النيتروجيني، واحمِ الأزهار من اضطراب الري والحرارة.", water: "متوسط إلى مرتفع في التأسيس وتكوين الثمار، مع خفض مدروس قرب النضج حسب التربة.", light: "شمس كاملة", diseases: ["البياض الدقيقي", "الأنثراكنوز", "أعفان الجذور", "العفن السخامي المرتبط بالحشرات"], pests: ["ذبابة الفاكهة", "البق الدقيقي", "الحشرات القشرية", "التربس"], control: "تهوية وتقليم ونظافة وإزالة الثمار المصابة ومراقبة الحشرات، مع عدم استخدام أي مبيد غير مسجل للمحصول في بلدك.", sources: [faoCalendar, plantwise, faoWater] } },
  { category: "tree", nameAr: "الجوافة", nameEn: "Guava", scientificName: "Psidium guajava", summaryAr: "شجرة دافئة سريعة النمو نسبيًا، تتضرر من الصقيع وتحتاج صرفًا جيدًا وحماية من ذباب الفاكهة.", summaryEn: "A warm-climate, relatively fast-growing tree that is frost-sensitive and needs good drainage and fruit-fly protection.", growingData: { countries: ["مصر", "السعودية", "قطر", "فلسطين"], planting: "تزرع الشتلات في الربيع أو بداية الموسم الدافئ، وتنجح في المناطق الدافئة مع حماية من البرد والرياح في البداية.", care: "قلّم للتشكيل وتجديد الأفرع، نظم الري، غطِّ التربة عضويًا دون ملامسة الجذع، واحصد الثمار على درجة النضج المناسبة.", water: "متوسط؛ يتأثر الإنتاج بالعطش ثم الري الغزير المفاجئ.", light: "شمس كاملة", diseases: ["الأنثراكنوز", "أعفان الثمار", "تبقعات الأوراق", "تعفن الجذور"], pests: ["ذبابة الفاكهة", "البق الدقيقي", "المنّ", "الحشرات القشرية"], control: "اجمع الثمار الساقطة، استخدم المصائد والوقاية والنظافة، وافحص الأوراق والثمار دوريًا قبل اتخاذ أي إجراء.", sources: [faoCalendar, plantwise] } },
];
