import { PlatformShell } from "@/components/PlatformShell";
import { Button } from "@/components/ui/button";
import { useCart } from "@/contexts/CartContext";
import { useLanguage } from "@/lib/i18n";
import { trpc } from "@/lib/trpc";
import type { Product } from "@shared/commerce/types";
import { CheckCircle2, Leaf, Loader2, ShoppingBag, Sprout } from "lucide-react";
import { toast } from "sonner";

function price(product: Product, locale: string) { return new Intl.NumberFormat(locale, { style: "currency", currency: product.priceRange.min.currencyCode, maximumFractionDigits: 2 }).format(Number(product.priceRange.min.amount)); }

export default function Shop() {
  const { language } = useLanguage(); const { addItem, loading } = useCart();
  const products = trpc.commerce.products.list.useQuery({ first: 12 });
  const isArabic = language === "ar";
  const addToCart = async (product: Product) => { const variant = product.variants[0]; if (!variant?.availableForSale) return; try { await addItem(variant.id); toast.success(isArabic ? "تمت إضافة المنتج إلى السلة" : "Product added to your cart"); } catch (error) { toast.error(error instanceof Error ? error.message : isArabic ? "تعذر تحديث السلة" : "Unable to update the cart"); } };
  return <PlatformShell title={isArabic ? "المتجر الزراعي" : "Agricultural store"} eyebrow={isArabic ? "منتجات مختارة لاحتياجات العناية والري والمتابعة" : "Selected essentials for care, irrigation, and monitoring"}><main className="container py-8"><section className="grid gap-5 rounded-[1.7rem] bg-[#35530e] p-6 text-white md:grid-cols-[1.3fr_.7fr] md:items-end sm:p-8"><div><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold text-[#e0edcf]"><Leaf className="size-3.5" />{isArabic ? "متجر مرتبط بسلة ودفع آمن" : "Live cart and secure checkout"}</span><h2 className="mt-5 text-3xl font-bold leading-tight">{isArabic ? "اختَر ما يدعم قرارك، وليس مجرد منتج." : "Choose what supports your decision, not just a product."}</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-[#dce8c9]">{isArabic ? "اعرض منتجات الري والمتابعة بعناية. استخدم خطة موقعك واطلب مراجعة خبير قبل أي شراء يؤثر في تصميم أو معالجة حساسة." : "Browse irrigation and monitoring essentials thoughtfully. Use your site plan and seek expert review before purchases that affect a sensitive design or treatment."}</p></div><div className="rounded-2xl bg-white/10 p-4 text-sm leading-6 text-[#e8f1dc]"><CheckCircle2 className="mb-2 size-5 text-[#bcd88b]" />{isArabic ? "يتم إتمام الدفع من خلال صفحة المتجر الآمنة، مع بقاء بيانات البطاقة خارج المنصة." : "Checkout continues on the secure storefront, keeping payment card data outside the platform."}</div></section>
  {products.isLoading ? <div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 2 }).map((_, index) => <div key={index} className="h-96 animate-pulse rounded-[1.6rem] bg-white" />)}</div> : products.error ? <div className="mt-7 rounded-[1.5rem] border border-[#e9c5bd] bg-[#fff8f6] p-6 text-[#8c4a3c]">{isArabic ? "تعذر تحميل المتجر حاليًا. حاول مرة أخرى بعد قليل." : "The store could not load right now. Please try again shortly."}</div> : products.data?.length ? <div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.data.map(product => <ProductCard key={product.id} product={product} isArabic={isArabic} disabled={loading} add={() => addToCart(product)} />)}</div> : <section className="mt-7 rounded-[1.6rem] border border-dashed border-[#c3d4ae] bg-white p-10 text-center"><Sprout className="mx-auto size-9 text-[#86a957]" /><h2 className="mt-4 text-xl font-bold text-[#41562a]">{isArabic ? "يتم تجهيز المنتجات المختارة" : "Selected products are being prepared"}</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-[#718062]">{isArabic ? "سيظهر هنا كتالوج المتجر فور نشر المنتجات في قناة البيع. يمكنك استخدام التخطيط والتحليل الآن." : "The live catalog will appear here once products are published to the sales channel. You can use planning and analysis in the meantime."}</p></section>}</main></PlatformShell>;
}

function ProductCard({ product, isArabic, disabled, add }: { product: Product; isArabic: boolean; disabled: boolean; add: () => void }) {
  const variant = product.variants[0]; const image = product.images[0];
  return <article className="overflow-hidden rounded-[1.6rem] border border-[#35530e]/10 bg-white shadow-[0_12px_30px_rgba(48,67,22,.05)]"><div className="relative aspect-square bg-[#eff4e9]">{image?.url ? <img src={image.url} alt={image.altText || product.title} className="size-full object-cover" /> : <div className="grid size-full place-items-center"><Sprout className="size-10 text-[#78994d]" /></div>}<span className="absolute end-3 top-3 rounded-full bg-white/90 px-2.5 py-1 text-[10px] font-bold text-[#5c7440] backdrop-blur">{product.productType || (isArabic ? "زراعة ذكية" : "Smart growing")}</span></div><div className="p-5"><h2 className="text-lg font-bold text-[#304515]">{product.title}</h2><p className="mt-2 line-clamp-2 min-h-10 text-sm leading-5 text-[#6f7e60]">{product.description || (isArabic ? "منتج مختار لدعم احتياجات العناية الزراعية." : "A selected essential for agricultural care needs.")}</p><div className="mt-5 flex items-center justify-between gap-3"><span className="text-lg font-bold text-[#35530e]">{price(product, isArabic ? "ar" : "en")}</span><Button onClick={add} disabled={!variant?.availableForSale || disabled} className="h-10 rounded-xl bg-[#35530e] text-xs text-white hover:bg-[#294108]">{disabled ? <Loader2 className="size-4 animate-spin" /> : <ShoppingBag className="size-4" />}{isArabic ? "أضف للسلة" : "Add to cart"}</Button></div></div></article>;
}
